build prod issue fixes
Fixing:
ERROR in src/app/project/add-project/add-project.component.html(40,25): : Property 'max' does not exist on type 'AddProjectComponent'.
src/app/project/add-project/add-project.component.html(40,37): : Property 'min' does not exist on type 'AddProjectComponent'.